<?php
/**
 * 网站配置文件
 */
return $config = [
    'db'            => [
        'dbtype'    => 'mysql',
        'host'      => '120.24.214.209',
        'user'      => 'blog',
        'passwd'    => 'blog',
        'port'      => 3306,
        'dbname'    => 'p_blog'
    ],
    'smtp'          => [
        'port'          => 25,
        'timeout'       => 100,
        'logfile'       => 'mail.log',
        'smtpserver'    => 'smtp.mxhichina.com',
        'auth'          => true,
        'host'          => 'http://120.24.214.209',
        'user'          => 'caohd@caohdgg.xyz',
        'password'      => 'Adg_200910221',
    ],
    'nologin'       => [
        '/index.html',
        '/login.html',
        '/test.html',
        '/403.html',
        '/t1.html',
        '/upload.html',
        '/finish.html',
        '/search.html',
    ],
    'manager'       => [
        'User:getCurUserInfo',
        'User:allLocations',
        'User:upl',
        'User:saveLogo',
        'User:updateUser',
        'User:changePassword',
        'Mail:checkEmail',
        'Mail:changeBindEmail',
        'User:finish',
        'User:init',
        'Article:delete',
        'Index:loadMore',
        'Like:ILike',
        'User:changeBrief',
        'Comment:loadComment',
        'Comment:macomment',
        'User:infoInit',
        'User:getUserInfo',
        'Login:truePassword',
        'Relation:init',
        'Relation:cancelConcern',
        'Relation:cancelShip',
        'Relation:concern',
        'Relation:addConcern',
        'Like:init',
        'Comment:cComment',
        'Album:init',
        'Album:creatNewAlbum',
        'Album:delete',
        'Picture:allPictures',
        'World:init',
        'World:loadMore',
        'Article:reprint',
        'Article:moreReader',
        'Article:getByMAId',
        'Picture:addPicToAlbum',
        'Picture:getPicInfoBySrc',
        'Picture:delete',
        'Picture:likePic',
        'Picture:rmLike',
        'Message:init',
        'Chat:deleteChats',
    ]
];